### ISSUE TITLE
text dataset question？

### ISSUE THREAD

**Issue by AmoAonA** [suliangxu/MACA#1]
Is the text description you used from https://github.com/Dacun/Text-based-Person-Search? However, we found that its dataset is incomplete in both datasets. There are 1,460 unlabeled images in the training set of CUHK-SYSU and 40 unlabeled images in PRW. Can you open the text data first?

**Comment by suliangxu** [comment]
> Is the text description you used from https://github.com/Dacun/Text-based-Person-Search? However, we found that its dataset is incomplete in both datasets. There are 1,460 unlabeled images in the training set of CUHK-SYSU and 40 unlabeled images in PRW. Can you open the text data first?

Yes, you are right.  Not all the images in CUHK-SYSU are selected in CUHK-SYSU-TBPS dataset.

The size of the training set:
CUHK-SYSU-TBPS:  15080*2 descriptions and 9716 images
PRW-TBPS:   14897 descriptions and 5134 images.

And I only used the labeled data to train the model.

**Comment by AmoAonA** [comment]
PRW-TBPS train set should be 5664 images.

**Comment by AmoAonA** [comment]
> > Is the text description you used from https://github.com/Dacun/Text-based-Person-Search? However, we found that its dataset is incomplete in both datasets. There are 1,460 unlabeled images in the training set of CUHK-SYSU and 40 unlabeled images in PRW. Can you open the text data first?
> 
> Yes, you are right. Not all the images in CUHK-SYSU are selected in CUHK-SYSU-TBPS dataset.
> 
> The size of the training set: CUHK-SYSU-TBPS: 15080*2 descriptions and 9716 images PRW-TBPS: 14897 descriptions and 5134 images.
> 
> And I only used the labeled data to train the model.

PRW-TBPS train set should be 5664 images.
