### ISSUE TITLE
About code release

### ISSUE THREAD

**Issue by shuanglinyan** [suliangxu/MACA#2]
Hi. Thank you for your great work. Can I ask when you are planning to release the code?

**Comment by suliangxu** [comment]
> Hi. Thank you for your great work. Can I ask when you are planning to release the code?

Thanks for your attention, the code will be released within two weeks.

**Comment by CTH513** [comment]
When will the code be open source?

**Comment by suliangxu** [comment]
The code has been released. Thanks!
